version: '3'
services:
  db:
    build: .
    ports:
      - ${PORT}:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - DB_NAME=${DB_NAME}
  builder:
    build: 
      context: .
      dockerfile: Dockerfile.builder
    links:
      - db
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - SA_PASSWORD=${SA_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db