version: '3'
services:
  db:
    build: .
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
      - DB_NAME=Mountain
    networks:
      - deploy
  builder:
    build: 
      context: .
      dockerfile: Dockerfile.builder
    links:
      - db
    environment:
      - PORT=1433
      - DB_HOST=db
      - SA_PASSWORD=P@ssw0rd
      - DB_NAME=Mountain
    depends_on:
      - db
    networks:
      - deploy
networks:
  deploy: